import {api,roomCode,node} from '../live/shared.js';
const $=s=>document.querySelector(s),code=roomCode();let state=null,busy=false,lastRoll=null,offset=0;
const colors=['#de8670','#83a6d3','#b8a0d3','#92bd86','#e6ae63','#61b5ad'];
$('#join-qr').src=`/api/game?action=monopolyQr&room=${code}`;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function error(e){$('#message').textContent=e.message;$('#message').className='notice bad';}
function renderBoard(positions){const ps=state.players||[],path=[];for(let x=0;x<8;x++)path.push([x,0]);for(let y=0;y<8;y++)path.push([8,y]);for(let x=8;x>0;x--)path.push([x,8]);for(let y=8;y>0;y--)path.push([0,y]);const n=state.boardLength||30;const visible=path.slice(0,n);$('#board').replaceChildren(...visible.map(([x,y],i)=>{const e=node('div','space');Object.assign(e.style,{left:x*100/9+'%',top:y*100/9+'%',width:100/9+'%',height:100/9+'%'});e.style.setProperty('--stripe',colors[i%colors.length]);e.style.setProperty('--tile-color',['#fff0dc','#e0eefb','#f4e4f5','#e3f2dc'][i%4]);e.append(node('span','space-number',i?'ช่อง '+(i+1):'เริ่มต้น'));const tokens=node('div','tokens');ps.forEach((p,k)=>{const pos=positions?.[p.id]??p.position;if(pos===i+1){const t=node('span','token',k+1);t.title=p.name;t.style.background=colors[k%colors.length];tokens.append(t);}});e.append(tokens);return e;}));}
function render(){if(!state)return;const ps=state.players||[],r=state.lastRoll;$('#title').textContent=state.title;$('#turn-label').textContent=state.winner?'🏆 '+state.winner.name+' ชนะเกม!':`ตาของ ${ps[state.turn]?.name||'ทีมถัดไป'}`;$('#member-count').textContent=state.participantCount||0;$('#roll').disabled=busy||!!state.winner||!!(r&&r.phase!=='resolved');$('#roll').textContent=busy?'กำลังดำเนินการ…':'ทอยลูกเต๋า';$('#players').replaceChildren(...ps.map((p,i)=>{const e=node('div','score-chip',`${i+1}. ${p.name} · ${p.points||0}`);e.style.setProperty('--team-color',colors[i%colors.length]);return e;}));renderBoard();const q=r?.question;$('#question-card').hidden=!q||r.phase!=='question';if(q&&r.phase==='question'){if(q.image)$('#question-image').src=q.image;$('#question-image').hidden=!q.image;$('#question-title').textContent=q.title;$('#question-type').textContent=`ตอบพร้อมกันทุกทีม · เหลือ ${Math.max(0,Math.ceil((r.deadline-(Date.now()+offset))/1000))} วินาที`;}$('#hero').textContent=r?.hero?`ฮีโร่ล่าสุด: ${r.hero.name} · +${r.hero.score} คะแนน`:'ฮีโร่ล่าสุดจะแสดงหลังเฉลย';$('#message').textContent=r?.phase==='landing'?'กำลังเดินเบี้ย…':r?.phase==='question'?'ตอบคำถามจากมือถือได้เลย':r?.phase==='resolved'?(r.message||'จบเทิร์น'):'พร้อมเริ่มเกม';}
async function receive(next){state=next;render();if(next.lastRoll&&next.lastRoll.id!==lastRoll){lastRoll=next.lastRoll.id;busy=true;render();await wait(Math.max(700,(next.lastRoll.steps||0)*180));busy=false;render();}else render();}
async function tick(){try{const r=await api('monopolyTick',{room:code});if(!state||r.state.revision>=state.revision)await receive(r.state);}catch{}finally{setTimeout(tick,500);}}
async function roll(){if(busy)return;busy=true;render();try{const r=await api('monopolyRoll',{room:code});offset=r.serverNow-Date.now();await receive(r.state);$('#message').textContent='กำลังเดินเบี้ย…';}catch(e){busy=false;error(e);render();}}
$('#roll').onclick=roll;document.addEventListener('keydown',e=>{if(['Space','Enter','KeyR'].includes(e.code)&&!e.repeat){e.preventDefault();roll();}});
async function refresh(){try{const r=await api('monopolyPublic',{room:code},'',true);offset=r.serverNow-Date.now();if(!state||r.state.revision>=state.revision)await receive(r.state);}catch(e){error(e);}}
function renderLeaderboard(){let el=$('#leaderboard');if(!el){el=node('aside','leaderboard');el.id='leaderboard';$('#game')?.prepend(el);document.querySelector('.board-shell')?.before(el);}if(!el||!state)return;const rows=(state.participants||[]).slice().sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,5);el.replaceChildren(node('strong','leaderboard-title','🏆 ฮีโร่ของเกม'));rows.forEach((p,i)=>el.append(node('div','leader-row',`${i+1}. ${p.name} · ${p.score||0}`)));}
setInterval(renderLeaderboard,500);refresh();tick();
