import {api,config,node} from '../live/shared.js';const $=s=>document.querySelector(s);let auth,g;
async function run(fn){try{await fn();}catch(e){$('#notice').textContent=e.message;$('#notice').hidden=false;}}
async function load(){const r=await api('monopolyRooms',{},auth,true);$('#rooms').replaceChildren();for(const x of r.rooms){const row=node('div','room'),b=node('button','','จัดการ');row.append(node('strong','',x.title+' · '+x.code),b);b.onclick=()=>run(()=>open(x.code));$('#rooms').append(row);}}
const field=(parent,label,key,value,type='text')=>{const l=node('label','',label),e=node(type==='textarea'?'textarea':'input');if(type!=='textarea')e.type=type;e.dataset.k=key;e.value=value??'';l.append(e);parent.append(l);return e;};
function team(t={}){const row=node('div','room');row.dataset.id=t.id||'';field(row,'ชื่อทีม / ผู้เล่น','name',t.name);const b=node('button','secondary','ลบทีม');b.onclick=()=>row.remove();row.append(b);$('#teams').append(row);}
async function open(code){g=(await api('monopolyAdmin',{room:code},auth,true)).game;$('#editor').hidden=false;$('#title').value=g.title;$('#board-length').value=g.boardLength||g.spaces?.length||30;$('#room-title').textContent=g.title+' · '+code;$('#play').href=`play.html?room=${code}`;$('#teams').replaceChildren();Object.values(g.players||{}).forEach(team);$('#questions').value=(g.questionBank||[]).map(q=>q.type==='choice'?[q.type,q.title,...q.options,q.correct+1,q.seconds,...(q.image?['image='+encodeURIComponent(q.image)]:[])].join('|'):[q.type,q.title,q.answer,q.seconds,q.image||''].join('|')).join('\n');$('#spaces').replaceChildren();g.spaces.slice(0,Number($('#board-length').value)||30).forEach((x,i)=>{const card=node('div','edit-card');card.append(node('h3','',i?'ช่อง '+(i+1):'Start/Finish'));field(card,'ชื่อช่อง','title',x.title);field(card,'ข้อความประกอบ','text',x.text,'textarea');$('#spaces').append(card);});}
const heading=node('h2','','ทีม / ผู้เล่น'),add=node('button','secondary','+ เพิ่มทีม');add.onclick=()=>team();$('#spaces').before(heading,add);
$('#login-form').onsubmit=e=>{e.preventDefault();run(async()=>{auth=(await api('login',{password:$('#password').value})).token;$('#login').hidden=true;$('#app').hidden=false;await load();});};
$('#create').onclick=()=>run(async()=>{const r=await api('monopolyCreate',{},auth);await load();await open(r.game.code);});
$('#save').onclick=()=>run(async()=>{const spaces=[...$('#spaces').children].map(c=>({title:c.querySelector('[data-k="title"]').value,text:c.querySelector('[data-k="text"]').value}));const questions=$('#questions').value.split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const p=line.split('|').map(x=>x.trim()),type=p.shift(),title=p.shift();if(type==='choice'){const image=p.at(-1)?.startsWith('image=')?decodeURIComponent(p.pop().slice(6)):'';const seconds=Number(p.pop()),correct=Number(p.pop())-1;return {type,title,options:p,correct,seconds,image};}return {type,title,answer:p[0],seconds:Number(p[1]||10),image:p[2]||''};});await api('monopolySave',{room:g.code,title:$('#title').value,boardLength:Number($('#board-length').value),spaces,questions,teams:[...$('#teams').children].map(r=>({id:r.dataset.id,name:r.querySelector('input').value}))},auth);await open(g.code);$('#notice').textContent='บันทึกทีม กระดาน และคลังคำถามแล้ว';$('#notice').hidden=false;});
$('#reset').onclick=()=>{if(confirm('เริ่มทุกทีมใหม่จาก Start/Finish?'))run(async()=>{await api('monopolyReset',{room:g.code},auth);await open(g.code);});};config().catch(e=>run(()=>{throw e;}));
