import {api,config,node} from '../live/shared.js';const $=s=>document.querySelector(s);let auth,g;
async function run(fn){try{await fn();}catch(e){$('#notice').textContent=e.message;$('#notice').hidden=false;}}
async function load(){const r=await api('monopolyRooms',{},auth,true);$('#rooms').replaceChildren();for(const x of r.rooms){const row=node('div','room'),b=node('button','','จัดการ');row.append(node('strong','',x.title+' · '+x.code),b);b.onclick=()=>run(()=>open(x.code));$('#rooms').append(row);}}
const field=(parent,label,key,value,type='text')=>{const l=node('label','',label),e=node(type==='textarea'?'textarea':'input');if(type!=='textarea')e.type=type;e.dataset.k=key;e.value=value??'';l.append(e);parent.append(l);return e;};
function team(t={}){const row=node('div','room');row.dataset.id=t.id||'';field(row,'ชื่อทีม / ผู้เล่น','name',t.name);const b=node('button','secondary','ลบทีม');b.onclick=()=>row.remove();row.append(b);$('#teams').append(row);}
async function open(code){g=(await api('monopolyAdmin',{room:code},auth,true)).game;$('#editor').hidden=false;$('#title').value=g.title;$('#room-title').textContent=g.title+' · '+code;$('#play').href=`play.html?room=${code}`;$('#teams').replaceChildren();Object.values(g.players||{}).forEach(team);$('#spaces').replaceChildren();g.spaces.forEach((x,i)=>{const card=node('div','edit-card');card.append(node('h3','',i?'ช่อง '+(i+1):'Start/Finish'));field(card,'ชื่อช่อง','title',x.title);field(card,'ข้อความเมื่อเปิดป้าย','text',x.text,'textarea');field(card,'เดินหน้า (+) / ถอยหลัง (-) สำหรับช่องทั่วไป','move',x.move,'number');field(card,'คะแนน','points',x.points,'number');const enable=field(card,'ใช้คำถามในช่องนี้','quiz',null,'checkbox');enable.checked=!!x.question;const q=node('div');const v=x.question||{};field(q,'คำถาม','question',v.title,'textarea');field(q,'ตัวเลือก (หนึ่งบรรทัดต่อข้อ)','options',(v.options||[]).join('\n'),'textarea');field(q,'เฉลย: หมายเลขตัวเลือก เริ่มจาก 1','correct',(v.correct??0)+1,'number');field(q,'เวลาตอบ (วินาที)','seconds',v.seconds??5,'number');field(q,'ตอบถูก: เดินหน้ากี่ช่อง','forward',v.forward??3,'number');field(q,'ตอบผิด/หมดเวลา: ถอยหลังกี่ช่อง','backward',v.backward??2,'number');q.hidden=!enable.checked;enable.onchange=()=>q.hidden=!enable.checked;card.append(q);$('#spaces').append(card);});}
const teams=node('div');teams.id='teams';const heading=node('h2','','ทีม / ผู้เล่น'),add=node('button','secondary','+ เพิ่มทีม');add.onclick=()=>team();$('#spaces').before(heading,teams,add);
$('#login-form').onsubmit=e=>{e.preventDefault();run(async()=>{auth=(await api('login',{password:$('#password').value})).token;$('#login').hidden=true;$('#app').hidden=false;await load();});};
$('#create').onclick=()=>run(async()=>{const r=await api('monopolyCreate',{},auth);await load();await open(r.game.code);});
$('#save').onclick=()=>run(async()=>{const spaces=[...$('#spaces').children].map(c=>{const v=k=>c.querySelector(`[data-k="${k}"]`).value;const x={title:v('title'),text:v('text'),move:+v('move'),points:+v('points')};if(c.querySelector('[data-k=quiz]').checked)x.question={title:v('question'),options:v('options').split('\n').map(x=>x.trim()).filter(Boolean),correct:+v('correct')-1,seconds:+v('seconds'),forward:+v('forward'),backward:+v('backward')};return x;});await api('monopolySave',{room:g.code,title:$('#title').value,spaces,teams:[...$('#teams').children].map(r=>({id:r.dataset.id,name:r.querySelector('input').value}))},auth);await open(g.code);$('#notice').textContent='บันทึกทีมและกติกาแล้ว';$('#notice').hidden=false;});
$('#reset').onclick=()=>{if(confirm('เริ่มทุกทีมใหม่จาก Start/Finish?'))run(async()=>{await api('monopolyReset',{room:g.code},auth);await open(g.code);});};config().catch(e=>run(()=>{throw e;}));
