import test from 'node:test';
import assert from 'node:assert/strict';
import {newRoom,mutate,publicState,points,validateQuestion} from '../lib/engine.mjs';
const admin={role:'admin'}, player={role:'player',id:'p1'};
function setup(){const room=newRoom('ABC123',1000);mutate(room,'join',{name:'หนึ่ง',group:'กลุ่ม 1'},player,1100);mutate(room,'start',{questionId:'q1',newRoundId:'r1'},admin,2000);return room;}
test('no answer key or explanation leaks before reveal; freeze active question',()=>{const r=setup();const pub=publicState(r,2100);assert.equal(Object.hasOwn(pub.round,'correct'),false);assert.equal(Object.hasOwn(pub.round,'explanation'),false);assert.equal(pub.round.distribution,null);assert.throws(()=>mutate(r,'save',{questions:r.questions},admin,2200),/ปิดรอบ/);r.questions[0].correct=0;assert.equal(r.rounds.r1.question.correct,1);});
test('server deadline, immutable retry time, changes and speed bonus',()=>{const r=setup();mutate(r,'answer',{roundId:'r1',choice:0},player,3000);mutate(r,'answer',{roundId:'r1',choice:0},player,4000);assert.equal(r.rounds.r1.answers.p1.at,3000);mutate(r,'answer',{roundId:'r1',choice:1},player,5000);const a=r.rounds.r1.answers.p1;assert.equal(a.changes,1);assert.equal(points(a,r.rounds.r1,r.settings),145);assert.throws(()=>mutate(r,'answer',{roundId:'r1',choice:0},player,32000),/หมดเวลา/);assert.throws(()=>mutate(r,'answer',{roundId:'wrong',choice:0},player,7000),/หมดเวลา/);});
test('correct first choice receives steady bonus; wrong receives zero',()=>{const r=setup();const round=r.rounds.r1;assert.equal(points({choice:1,at:2000,changes:0},round,r.settings),200);assert.equal(points({choice:0,at:2000,changes:0},round,r.settings),0);});
test('scores appear only after reveal, averaged by all team members, reveal idempotence guarded',()=>{const r=setup();mutate(r,'join',{name:'สอง',group:'กลุ่ม 1'},{role:'player',id:'p2'},2200);mutate(r,'answer',{roundId:'r1',choice:1},player,5000);assert.equal(publicState(r,5100).leaderboard[0].score,0);mutate(r,'close',{},admin,6000);assert.throws(()=>mutate(r,'answer',{roundId:'r1',choice:0},player,6100));mutate(r,'reveal',{},admin,6200);const pub=publicState(r,6300);assert.equal(pub.leaderboard[0].score,195);assert.equal(pub.groupScores[0].score,98);assert.equal(pub.round.correct,1);assert.deepEqual(pub.round.distribution,[0,1]);assert.throws(()=>mutate(r,'reveal',{},admin,6400));});
test('opinions with absent Firebase null fields award zero',()=>{const r=setup();delete r.rounds.r1.question.correct;mutate(r,'answer',{roundId:'r1',choice:1},player,3000);mutate(r,'close',{},admin,4000);mutate(r,'reveal',{},admin,5000);assert.equal(publicState(r,5100).round.correct,null);assert.equal(publicState(r,5100).leaderboard[0].score,0);assert.equal(validateQuestion({...r.questions[0],correct:undefined}).correct,null);});
test('unauthorized players cannot operate room; invalid joins and options rejected',()=>{const r=setup();assert.throws(()=>mutate(r,'close',{},player,3000),/ผู้สอน/);assert.throws(()=>mutate(r,'join',{name:'หนึ่ง',group:'กลุ่ม 1'},{id:'p2'},3000),/ชื่อนี้/);assert.throws(()=>mutate(r,'join',{name:'สอง',group:'หายไป'},{id:'p2'},3000),/เลือกกลุ่ม/);assert.throws(()=>mutate(r,'answer',{roundId:'r1',choice:9},player,3000));assert.throws(()=>validateQuestion({...r.questions[0],image:'javascript:alert(1)'}));});
