import test from 'node:test';
import assert from 'node:assert/strict';
import {newMonopoly,mutateMonopoly,monopolyPublic} from '../lib/monopoly.mjs';
const admin={role:'admin'};
function game(){const g=newMonopoly('ABC123',0);g.questionBank=[{id:'q1',type:'choice',title:'เลือก',options:['ใช่','ไม่'],correct:0,seconds:10},{id:'q2',type:'number',title:'นับ',answer:7,seconds:10}];return g;}
function join(g,id,teamId,at=0){mutateMonopoly(g,'monopolyJoin',{name:id,teamId},{id,role:'player'},at);return {id,role:'player'};}
test('new games use 30 forward-only spaces and five teams',()=>{const g=game();assert.equal(g.spaces.length,30);assert.equal(g.boardLength,30);assert.equal(Object.keys(g.players).length,5);});
test('rolling twice is blocked until the question turn resolves',()=>{const g=game();mutateMonopoly(g,'monopolyRoll',{}, {},1);assert.throws(()=>mutateMonopoly(g,'monopolyRoll',{}, {},2));});
test('all teams can answer and the fastest correct team gets one bonus space',()=>{const g=game();g.questionBank=[g.questionBank[0]];const green=join(g,'green','team1');const red=join(g,'red','team0');mutateMonopoly(g,'monopolyRoll',{}, {},1);const r=g.lastRoll;mutateMonopoly(g,'monopolyTick',{}, {},3000);assert.equal(r.phase,'question');const before=g.players.team0.position;const slow=mutateMonopoly(g,'monopolyAnswer',{roundId:r.id,choice:0},green,4000);const fast=mutateMonopoly(g,'monopolyAnswer',{roundId:r.id,choice:0},red,3200);assert.ok(slow.answer.score<fast.answer.score);mutateMonopoly(g,'monopolyTick',{}, {},14000);assert.equal(g.lastRoll.phase,'resolved');assert.equal(g.players.team0.position,Math.min(30,before+1));assert.equal(g.lastRoll.hero.name,'red');});
test('wrong answers do not move teams and timeout ends the turn',()=>{const g=game();const player=join(g,'wrong','team0');mutateMonopoly(g,'monopolyRoll',{}, {},1);const r=g.lastRoll;mutateMonopoly(g,'monopolyTick',{}, {},3000);const pos=g.players.team0.position;mutateMonopoly(g,'monopolyAnswer',{roundId:r.id,choice:1},player,3500);mutateMonopoly(g,'monopolyTick',{}, {},14000);assert.equal(g.lastRoll.correct,false);assert.equal(g.players.team0.position,pos);assert.equal(g.turn,1);});
test('question bank is shuffled and public state never leaks answer keys',()=>{const g=game();mutateMonopoly(g,'monopolyRoll',{}, {},1);const pub=monopolyPublic(g);assert.equal(pub.lastRoll.question.correct,undefined);assert.equal(pub.lastRoll.question.answer,undefined);});
test('admin saves typed question formats and board length',()=>{const g=newMonopoly('ABC123',0);mutateMonopoly(g,'monopolySave',{title:'ใหม่',boardLength:24,spaces:Array.from({length:24},()=>({title:'ช่อง'})),questions:[{type:'choice',title:'เลือก',options:['ก','ข','ค','ง'],correct:2,seconds:5},{type:'image-count',title:'นับจุด',answer:7,seconds:15,image:'https://example.com/x.png'}],teams:[{id:'a',name:'ทีม A'}]},admin,1);assert.equal(g.boardLength,24);assert.equal(g.questionBank.length,2);assert.equal(g.questionBank[1].answer,7);});
