import {api,config,token,notify} from '../live/shared.js';
const $=s=>document.querySelector(s);let auth='',board=null;
function show(msg,bad=false){notify(msg,bad)}
async function load(){const r=await api('boardRooms',{},auth,true);const el=$('#rooms');el.replaceChildren();if(!r.rooms.length)el.innerHTML='<p class="sub">ยังไม่มีห้อง กดสร้างห้องใหม่เพื่อเริ่ม</p>';for(const x of r.rooms){const row=document.createElement('div');row.className='room';row.innerHTML=`<div><strong>${x.code}</strong><div class="sub">${x.title}</div></div><button data-code="${x.code}">จัดการ</button>`;row.querySelector('button').onclick=()=>open(x.code);el.append(row)}}
async function open(code,local=false){if(!local){const r=await api('boardAdmin',{room:code},auth,true);board=r.board;}$('#editor').hidden=false;$('#room-title').textContent=`${board.title} · ${code}`;$('#title').value=board.title;$('#play-link').href=`play.html?room=${code}`;const grid=$('#edit-grid');grid.replaceChildren();board.tiles.forEach((t,i)=>{const card=document.createElement('div');card.className='edit-card';card.innerHTML=`<strong>แผ่นป้าย ${i+1}</strong><label>หัวข้อ<input data-k="title" value=""></label><label>ข้อความ<textarea data-k="text" rows="3"></textarea></label><label>รูปภาพ URL<input data-k="image" placeholder="https://..."></label>`;card.querySelector('[data-k=title]').value=t.title;card.querySelector('[data-k=text]').value=t.text;card.querySelector('[data-k=image]').value=t.image;grid.append(card)})}
$('#login-form').onsubmit=async e=>{e.preventDefault();try{const r=await api('login',{password:$('#password').value});auth=r.token;localStorage.setItem('board-admin',auth);$('#login').hidden=true;$('#app').hidden=false;await load()}catch(e){show(e.message,true)}};
$('#create').onclick=async()=>{try{const r=await api('boardCreate',{},auth);await load();await open(r.board.code)}catch(e){show(e.message,true)}};
$('#save').onclick=async()=>{try{const cards=[...document.querySelectorAll('.edit-card')];const tiles=cards.map((c,i)=>({title:c.querySelector('[data-k=title]').value,text:c.querySelector('[data-k=text]').value,image:c.querySelector('[data-k=image]').value}));await api('boardSave',{room:board.code,title:$('#title').value,tiles},auth);await open(board.code);show('บันทึกห้องแล้ว')}catch(e){show(e.message,true)}};
$('#reset').onclick=async()=>{if(!confirm('ปิดแผ่นป้ายทั้งหมดเพื่อเริ่มกลุ่มใหม่หรือไม่'))return;try{await api('boardReset',{room:board.code},auth);await open(board.code)}catch(e){show(e.message,true)}};
const saved=localStorage.getItem('board-admin');if(saved){auth=saved;config().then(()=>{ $('#login').hidden=true;$('#app').hidden=false;load().catch(()=>localStorage.removeItem('board-admin'))})}else config();

$('#add-tile').onclick=()=>{if(board.tiles.length>=200)return show('เพิ่มได้สูงสุด 200 แผ่น',true);board.tiles.push({id:board.tiles.length+1,title:'',text:'',image:'',opened:false});open(board.code,true)};
