import { randomInt } from 'node:crypto';import {assert,GameError} from './engine.mjs';const clean=(v,m=300)=>String(v??'').trim().slice(0,m);
export function newMonopoly(code,now){return {type:'monopoly',code,title:'เกมเศรษฐี',createdAt:now,updatedAt:now,spaces:Array.from({length:25},(_,i)=>({id:i+1,title:i===0?'Start/Finish':`ช่อง ${i+1}`,text:'',move:0,points:0})),players:{},turn:0,lastRoll:null,revision:0};}
export function monopolyPublic(g,now=Date.now()){return {type:'monopoly',code:g.code,title:g.title,spaces:g.spaces.map((x,i)=>i===0?{...x,title:'Start/Finish'}:x),winner:g.winner||null,players:Object.values(g.players||{}),turn:g.turn,lastRoll:g.lastRoll??null,revision:g.revision,serverNow:now};}
export function mutateMonopoly(g,a,d,actor,now){assert(g?.type==='monopoly','ไม่พบห้องเกมเศรษฐี',404);g.players ||= {};if(a==='monopolyJoin'){const name=clean(d.name,40);assert(name,'กรุณาใส่ชื่อ');const id=clean(d.playerId,60)||`${Date.now()}-${randomInt(99999)}`;g.players[id] ||= {id,name,position:1,points:0};g.revision++;g.public=monopolyPublic(g,now);return {player:g.players[id],playerId:id};}if(a==='monopolyRoll'){assert(!g.winner,'เกมจบแล้ว กรุณาเริ่มกระดานใหม่',409);const id=clean(d.playerId,60);assert(g.players[id],'ไม่พบผู้เล่น');const ids=Object.keys(g.players);assert(ids[g.turn%ids.length]===id,'รอผู้เล่นคนอื่นทอยลูกเต๋า');const roll=randomInt(1,7),p=g.players[id],from=p.position;const n=g.spaces.length;
let progress=(p.progress??from-1)+roll;
let next=progress>=n?1:progress+1;
const space=g.spaces[next-1];
if(progress<n){p.points+=Number(space.points)||0;progress=Math.max(0,progress+(Number(space.move)||0));}
p.progress=Math.min(n,progress);p.position=progress>=n?1:progress+1;
if(progress>=n)g.winner={id,name:p.name,at:now};
g.lastRoll={at:now,player:id,name:p.name,roll,from,to:p.position,spaceId:next,steps:Math.min(roll,n-(from-1)),message:next===1?'ถึงเส้นชัยแล้ว!':space.text||space.title};
g.turn=(g.turn+1)%ids.length;g.revision++;g.updatedAt=now;g.public=monopolyPublic(g,now);return {result:g.lastRoll};}assert(actor?.role==='admin','เฉพาะผู้สอนเท่านั้น',403);if(a==='monopolySave'){g.title=clean(d.title,100)||g.title;assert(Array.isArray(d.spaces)&&d.spaces.length>=2&&d.spaces.length<=200,'ต้องมีช่อง 2–200 ช่อง');g.spaces=d.spaces.map((x,i)=>({id:i+1,title:clean(x.title,100)||`ช่อง ${i+1}`,text:clean(x.text,5000),move:Number(x.move)||0,points:Number(x.points)||0}));}else if(a==='monopolyReset'){Object.values(g.players).forEach(p=>{p.position=1;p.progress=0;p.points=0});g.turn=0;g.lastRoll=null;g.winner=null;}else throw new GameError('ไม่รู้จักคำสั่ง');g.revision++;g.updatedAt=now;g.public=monopolyPublic(g,now);return {};}
