import {randomInt,randomUUID} from 'node:crypto';
import {assert,GameError} from './engine.mjs';
const clean=(v,n=1000)=>String(v??'').trim().slice(0,n);
const num=(v,min,max)=>{const n=Number(v);assert(Number.isInteger(n)&&n>=min&&n<=max,`กรอกจำนวนเต็ม ${min}–${max}`);return n;};
const blank=i=>({id:i+1,title:i?'ช่อง '+(i+1):'Start/Finish',text:'',move:0,points:0});
export function normalize(g){assert(g,'ไม่พบห้อง',404);g.players||={};if(g.lastRoll&&!g.lastRoll.phase)g.lastRoll.phase='resolved';g.spaces=Array.from({length:40},(_,i)=>({...blank(i),...g.spaces?.[i],id:i+1}));return g;}
export function newMonopoly(code,now){return {type:'monopoly',code,title:'เกมเศรษฐี',createdAt:now,spaces:Array.from({length:40},(_,i)=>blank(i)),players:Object.fromEntries(Array.from({length:5},(_,i)=>['team'+i,{id:'team'+i,name:'ทีม '+(i+1),position:1,points:0}])),turn:0,revision:0};}
export function monopolyPublic(g,now=Date.now()){normalize(g);const r=g.lastRoll;return {code:g.code,title:g.title,spaces:g.spaces.map((x,i)=>({id:x.id,title:i?'ช่อง '+(i+1):'Start/Finish'})),players:Object.values(g.players),turn:g.turn,winner:g.winner||null,lastRoll:r?{...r,question:r.question?{title:r.question.title,options:r.question.options}:null}:null,revision:g.revision,serverNow:now};}
function finish(g,r,correct,now){const p=g.players[r.player],move=r.question?(correct?r.question.forward:-r.question.backward):r.move;const progress=Math.max(0,p.position-1+move);p.position=progress>=40?1:progress+1;p.points+=r.points||0;r.to=p.position;r.phase='resolved';r.correct=correct;r.message=r.question?(correct?'ตอบถูก':'ตอบผิดหรือหมดเวลา'):r.message;if(progress>=40)g.winner={id:p.id,name:p.name,at:now};g.turn=(g.turn+1)%Object.keys(g.players).length;}
export function settle(g,now){normalize(g);const r=g.lastRoll;if(r?.phase==='question'&&now>=r.deadline){finish(g,r,false,now);g.revision++;}g.public=monopolyPublic(g,now);}
export function mutateMonopoly(g,a,d,actor,now){normalize(g);settle(g,now);let result={};const active=g.lastRoll&&g.lastRoll.phase!=='resolved';
 if(a==='monopolyTick')return {};
 if(a==='monopolyRoll'){assert(!g.winner,'เกมจบแล้ว',409);assert(!active,'รอรอบปัจจุบันจบก่อน',409);const p=Object.values(g.players)[g.turn];assert(p,'ผู้สอนต้องเพิ่มทีมก่อน');const roll=randomInt(1,7),from=p.position,steps=Math.min(roll,41-from),pos=from+roll;p.position=pos>40?1:pos;const x=g.spaces[p.position-1];g.lastRoll={id:randomUUID(),at:now,player:p.id,name:p.name,roll,from,steps,to:p.position,spaceId:p.position,phase:'landing',readyAt:now+1400+steps*180,message:x.text||x.title,move:x.move||0,points:x.points||0,question:x.question||null};if(pos>40){g.winner={id:p.id,name:p.name,at:now};g.lastRoll.phase='resolved';g.lastRoll.message='ถึงเส้นชัยแล้ว!';}}
 else if(a==='monopolyAnswer'||a==='monopolyContinue'){const r=g.lastRoll;assert(r&&r.id===d.roundId,'รอบนี้สิ้นสุดแล้ว',409);if(r.phase==='resolved')return {};assert(now>=r.readyAt,'รอเดินถึงช่องก่อน',409);if(r.phase==='landing'&&r.question){r.phase='question';r.deadline=now+r.question.seconds*1000;}else if(r.phase==='question'){assert(a==='monopolyAnswer','เลือกคำตอบก่อน');const choice=num(d.choice,0,r.question.options.length-1);finish(g,r,now<r.deadline&&choice===r.question.correct,now);}else finish(g,r,null,now);}
 else {assert(actor?.role==='admin','เฉพาะผู้สอน',403);if(a==='monopolyReset'){Object.values(g.players).forEach(p=>{p.position=1;p.points=0;});g.turn=0;g.lastRoll=null;g.winner=null;}
 else if(a==='monopolySave'){assert(!active,'จบรอบปัจจุบันก่อนแก้ไข',409);g.title=clean(d.title,100)||g.title;assert(d.spaces?.length===40,'ต้องมี 40 ช่อง');g.spaces=d.spaces.map((x,i)=>{const v={...blank(i),title:clean(x.title,100),text:clean(x.text),move:num(x.move||0,-39,39),points:num(x.points||0,-10000,10000)};if(x.question){const q=x.question;assert(q.options?.length>=2&&q.options.length<=6,'คำถามต้องมี 2–6 ตัวเลือก');v.question={title:clean(q.title),options:q.options.map(o=>clean(o,200)),correct:num(q.correct,0,q.options.length-1),seconds:num(q.seconds,1,300),forward:num(q.forward,0,39),backward:num(q.backward,0,39)};assert(v.question.title&&v.question.options.every(Boolean),'กรอกคำถามและตัวเลือกให้ครบ');}return v;});
 if(d.teams){assert(d.teams.length>0&&d.teams.length<=60,'กำหนด 1–60 ทีม');const current=Object.values(g.players)[g.turn]?.id;g.players=Object.fromEntries(d.teams.map(t=>{const id=clean(t.id,60)||randomUUID();assert(clean(t.name,40),'กรอกชื่อทีม');return [id,{...(g.players[id]||{position:1,points:0}),id,name:clean(t.name,40)}];}));g.turn=Math.max(0,Object.keys(g.players).indexOf(current));}}
 else throw new GameError('ไม่รู้จักคำสั่ง');}
 g.revision++;g.updatedAt=now;g.public=monopolyPublic(g,now);return result;
}
