import {randomInt,randomUUID} from 'node:crypto';
import {assert,GameError} from './engine.mjs';
import {defaultMonopolyQuestions,addHumanAiQuestions} from './monopoly-questions.mjs';
const clean=(v,n=1000)=>String(v??'').trim().slice(0,n);
const num=(v,min,max)=>{const n=Number(v);assert(Number.isInteger(n)&&n>=min&&n<=max,`กรอกจำนวนเต็ม ${min}–${max}`);return n;};
const blank=i=>({id:i+1,title:i?'ช่อง '+(i+1):'Start/Finish',text:'',points:0});
export function normalize(g){assert(g,'ไม่พบห้อง',404);g.players||={};g.participants||={};g.questionBank||=[];g.questionOrder||=[];g.questionCursor||=0;g.boardLength||=g.spaces?.length||30;g.spaces=Array.from({length:g.boardLength},(_,i)=>({...blank(i),...g.spaces?.[i],id:i+1}));if(g.lastRoll&&!g.lastRoll.phase)g.lastRoll.phase='resolved';if(!g.questionBank.length)g.questionBank=g.spaces.flatMap(x=>x.question?[{...x.question,type:x.question.type||'choice',id:randomUUID()}]:[]);if(!g.questionBank.length&&!g.questionsConfigured){g.questionBank=defaultMonopolyQuestions();g.questionOrder=[];g.questionCursor=0;g.questionsConfigured=true;}addHumanAiQuestions(g);return g;}
export function newMonopoly(code,now){return {type:'monopoly',code,title:'เกมเศรษฐี',createdAt:now,accepting:true,boardLength:30,spaces:Array.from({length:30},(_,i)=>blank(i)),questionBank:defaultMonopolyQuestions(),questionsConfigured:true,humanAiQuestionsVersion:1,questionOrder:[],questionCursor:0,players:Object.fromEntries(Array.from({length:5},(_,i)=>['team'+i,{id:'team'+i,name:'ทีม '+(i+1),position:1,points:0}])),participants:{},turn:0,revision:0};}
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};
function question(g){normalize(g);const available=g.questionBank.filter(q=>q.active!==false);if(!available.length)return null;if(g.questionCursor>=g.questionOrder.length){g.questionOrder=shuffle(available.map(q=>q.id));g.questionCursor=0;}let id=g.questionOrder[g.questionCursor++],picked=available.find(q=>q.id===id);if(!picked){g.questionOrder=shuffle(available.map(q=>q.id));g.questionCursor=0;id=g.questionOrder[g.questionCursor++];picked=available.find(q=>q.id===id);}return picked||null;}
const safeQuestion=q=>{if(!q)return null;const {correct,answer,...safe}=q;return safe;};
export function monopolyPublic(g,now=Date.now()){normalize(g);const r=g.lastRoll;const publicRoll=r?Object.fromEntries(Object.entries(r).filter(([key])=>key!=='answers')):null;return {code:g.code,title:g.title,accepting:g.accepting!==false,boardLength:g.boardLength,spaces:g.spaces.map((x,i)=>({id:x.id,title:x.title||(i?'ช่อง '+(i+1):'Start/Finish'),text:x.text||'',points:x.points||0})),players:Object.values(g.players).map(p=>({...p,members:Object.values(g.participants).filter(m=>m.teamId===p.id).length})),participants:Object.values(g.participants).map(p=>({id:p.id,name:p.name,teamId:p.teamId,score:p.score||0})),participantCount:Object.keys(g.participants).length,turn:g.turn,winner:g.winner||null,lastRoll:r?{...publicRoll,question:safeQuestion(r.question)}:null,revision:g.revision,serverNow:now};}
function score(r,now){const limit=Math.max(1,(r.question.seconds||10)*1000),elapsed=Math.max(0,Math.min(limit,now-r.questionStartedAt));return Math.round(100+100*Math.pow(Math.max(0,1-elapsed/limit),1.6));}
function matches(q,d){if(q.type==='number'||q.type==='image-count')return Number.isInteger(Number(d.answer))&&Number(d.answer)===Number(q.answer);if(q.type==='boolean')return String(d.answer).toLowerCase()===String(q.answer).toLowerCase();if(q.type==='text')return clean(d.answer,300).toLowerCase()===clean(q.answer,300).toLowerCase();return Number.isInteger(Number(d.choice))&&Number(d.choice)===Number(q.correct);}
function resolve(g,r,now){if(r.phase==='resolved')return;const hero=Object.values(r.answers||{}).filter(a=>a.correct).sort((a,b)=>a.at-b.at)[0];if(hero){const team=g.players[hero.teamId];if(team){team.position=Math.min(g.boardLength,team.position+1);team.points=(team.points||0)+hero.score;}r.bonusTeamId=hero.teamId;r.bonusMove=1;}r.hero=hero?{participantId:hero.participantId,name:hero.name,teamId:hero.teamId,score:hero.score}:null;r.phase='resolved';r.correct=!!hero;r.resolvedAt=now;r.message=hero?'มีผู้ตอบถูกแล้ว':'หมดเวลา ไม่มีคำตอบถูก';g.turn=(g.turn+1)%Math.max(1,Object.keys(g.players).length);}
export function settle(g,now){normalize(g);const r=g.lastRoll;if(!r)return;if(r.phase==='landing'&&now>=r.readyAt){if(!r.question){r.phase='resolved';g.turn=(g.turn+1)%Math.max(1,Object.keys(g.players).length);}else{r.phase='question';r.questionStartedAt=now;r.deadline=now+(r.question.seconds||10)*1000;r.answers={};}}if(r.phase==='question'&&now>=r.deadline)resolve(g,r,now);g.public=monopolyPublic(g,now);}
export function mutateMonopoly(g,a,d,actor,now){normalize(g);settle(g,now);if(a==='monopolyReset')g.participants={};let result={};const r=g.lastRoll,active=r&&r.phase!=='resolved';
if(a==='monopolyTick')return {};
if(a==='monopolyJoin'){assert(g.accepting!==false&&!g.winner,'ห้องนี้ปิดรับผู้เล่นแล้ว',409);assert(actor?.id,'ไม่พบผู้เล่น');const name=clean(d.name,40),teamId=clean(d.teamId,60);assert(name,'กรอกชื่อผู้เล่น');assert(g.players[teamId],'ไม่พบทีมที่เลือก');g.participants[actor.id]={id:actor.id,name,teamId,joinedAt:now,score:g.participants[actor.id]?.score||0};result.participant=g.participants[actor.id];}
else if(a==='monopolyRoll'){assert(!g.winner,'เกมจบแล้ว',409);assert(!active,'รอรอบปัจจุบันจบก่อน',409);const p=Object.values(g.players)[g.turn];assert(p,'ผู้สอนต้องเพิ่มทีมก่อน');assert(g.questionBank.length,'ยังไม่มีคำถาม กรุณาเพิ่มคำถามในหน้าจัดการก่อนทอย',409);const roll=randomInt(1,7),from=p.position,to=Math.min(g.boardLength,from+roll);p.position=to;g.lastRoll={id:randomUUID(),at:now,player:p.id,name:p.name,roll,from,steps:to-from,to,spaceId:to,phase:'landing',readyAt:now+1200+(to-from)*240,question:question(g),answers:{}};if(to>=g.boardLength){g.winner={id:p.id,name:p.name,at:now};g.lastRoll.phase='resolved';g.turn=(g.turn+1)%Math.max(1,Object.keys(g.players).length);}}
else if(a==='monopolyAnswer'){assert(r&&r.id===d.roundId,'รอบนี้สิ้นสุดแล้ว',409);assert(r.phase==='question','ยังไม่เปิดรับคำตอบ',409);assert(now<r.deadline,'หมดเวลาตอบแล้ว',409);assert(actor?.id,'ไม่พบผู้เล่น');const member=g.participants[actor.id];assert(member,'ยังไม่ได้เข้าร่วมเกม',403);r.answers||={};assert(!r.answers[actor.id],'ตอบคำถามข้อนี้ไปแล้ว',409);const correct=matches(r.question,d),points=correct?score(r,now):0;r.answers[actor.id]={participantId:actor.id,name:member.name,teamId:member.teamId,correct,score:points,at:now};if(correct)member.score=(member.score||0)+points;result.answer={correct,score:points};}
else if(a==='monopolyContinue'){assert(r&&r.id===d.roundId,'รอบนี้สิ้นสุดแล้ว',409);settle(g,now);}
else {assert(actor?.role==='admin','เฉพาะผู้สอน',403);if(a==='monopolyReset'){Object.values(g.players).forEach(p=>{p.position=1;p.points=0;});Object.values(g.participants).forEach(p=>p.score=0);g.turn=0;g.lastRoll=null;g.winner=null;g.questionOrder=[];g.questionCursor=0;}else if(a==='monopolySave'){assert(!active,'จบรอบปัจจุบันก่อนแก้ไข',409);g.title=clean(d.title,100)||g.title;g.boardLength=num(d.boardLength||30,10,60);g.spaces=Array.from({length:g.boardLength},(_,i)=>({...blank(i),...(d.spaces?.[i]||{}),id:i+1,title:clean(d.spaces?.[i]?.title,100)||blank(i).title}));assert(Array.isArray(d.questions)&&d.questions.length<=500,'คำถามไม่ถูกต้อง');g.questionsConfigured=true;g.questionBank=d.questions.map(q=>{const type=clean(q.type||'choice',30),out={id:clean(q.id,100)||randomUUID(),type,title:clean(q.title,1000),image:clean(q.image,2000),seconds:num(q.seconds||10,1,300)};if(type==='choice'){assert(q.options?.length>=2&&q.options.length<=6,'คำถามต้องมีตัวเลือก 2–6 ข้อ');out.options=q.options.map(x=>clean(x,300));out.correct=num(q.correct,0,out.options.length-1);}else if(type==='number'||type==='image-count')out.answer=num(q.answer,0,100000);else if(type==='boolean')out.answer=String(q.answer)==='true';else out.answer=clean(q.answer,300);assert(out.title,'กรอกคำถาม');return out;});g.questionOrder=[];g.questionCursor=0;if(d.teams){assert(d.teams.length>0&&d.teams.length<=60,'กำหนด 1–60 ทีม');const current=Object.values(g.players)[g.turn]?.id;g.players=Object.fromEntries(d.teams.map(t=>{const id=clean(t.id,60)||randomUUID();assert(clean(t.name,40),'กรอกชื่อทีม');return [id,{...(g.players[id]||{position:1,points:0}),id,name:clean(t.name,40)}];}));g.turn=Math.max(0,Object.keys(g.players).indexOf(current));}}else throw new GameError('ไม่รู้จักคำสั่ง');}
g.revision++;g.updatedAt=now;g.public=monopolyPublic(g,now);return result;}
