import {$,node,api,config,token,notify,subscribe,secondsLeft,joinUrl,copy,scoreList,csvDownload} from './shared.js';
let c, room, state, stop, editing, busy=false;
const auth=()=>token('workshop-admin');
const phaseNames={lobby:'รอเริ่ม',open:'เปิดรับคำตอบ',closed:'ปิดรับแล้ว',revealed:'เฉลยแล้ว',finished:'จบกิจกรรม'};
async function run(fn){if(busy)return;busy=true;try{await fn();}catch(e){notify(e.message,true);if(e.status===401)logout();}finally{busy=false;updateControls();}}
function logout(){localStorage.removeItem('workshop-admin');stop?.();$('#login-panel').hidden=false;$('#rooms-panel').hidden=true;$('#control').hidden=true;$('#logout').hidden=true;}
async function rooms(){stop?.();state=null;room=null;$('#control').hidden=true;$('#login-panel').hidden=true;$('#rooms-panel').hidden=false;$('#logout').hidden=false;const r=await api('rooms',{},auth(),true);const list=$('#room-list');list.replaceChildren();if(!r.rooms.length)list.append(node('p','muted','ยังไม่มีห้อง สร้างห้องแรกเพื่อเริ่มกิจกรรม'));r.rooms.forEach(r=>{const b=node('div','panel room-item');b.append(node('strong','',r.code),node('span','',r.title),node('small','muted',new Date(r.createdAt).toLocaleString('th-TH')));const actions=node('div','actions');const open=node('button','button','เปิดห้อง');open.onclick=()=>run(()=>openRoom(r.code));const del=node('button','danger','ลบห้อง');del.onclick=()=>run(async()=>{if(!confirm(`ลบห้อง ${r.code} และข้อมูลการเล่นทั้งหมดหรือไม่? การลบย้อนกลับไม่ได้`))return;await api('delete',{room:r.code},auth());notify('ลบห้องแล้ว');await rooms();});actions.append(open,del);b.append(actions);list.append(b);});}
async function loadRoom(){const r=await api('admin',{room:room.code},auth(),true);room=r.room;fillSettings();renderQuestions();}
async function openRoom(code){room={code};await loadRoom();$('#rooms-panel').hidden=true;$('#control').hidden=false;$('#room-title').textContent=room.title;$('#code').textContent=code;$('#display-link').href=`display.html?room=${code}`;stop?.();stop=subscribe(code,c,s=>{state=s;$('#room-title').textContent=s.title;$('#participants').textContent=s.playerCount;$('#answered').textContent=s.round?.total||0;$('#current-question').textContent=s.round?.title||'เลือกคำถามเพื่อเริ่มรอบแรก';scoreList($('#admin-leaders'),s.leaderboard);scoreList($('#admin-groups'),s.groupScores,true);updateControls();});}
function fillSettings(){const s=room.settings;$('#setting-title').value=room.title;$('#setting-groups').value=room.groups.join('\n');for(const k of ['base','speed','steady','capacity'])$(`#setting-${k}`).value=s[k];$('#setting-distribution').checked=s.showDistribution;$('#setting-shuffle').checked=!!s.shuffleQuestions;}
function updateControls(){if(!state)return;const left=secondsLeft(state),phase=state.phase;$('#timer').textContent=phase==='open'?`${left}s`:'—';$('#phase').textContent=phase==='open'&&left===0?'หมดเวลา':phaseNames[phase];$('#next-question').disabled=busy||!['lobby','revealed'].includes(phase)||state.round?.number>=state.questionCount;$('#close-round').disabled=busy||phase!=='open';$('#reveal').disabled=busy||!(phase==='closed'||phase==='open'&&left===0);$('#finish').disabled=busy||['open','closed','finished'].includes(phase);$('#admission').disabled=busy||phase==='finished';$('#admission').textContent=state.accepting?'ปิดรับผู้เล่น':'เปิดรับผู้เล่น';for(const e of $('#settings-form').elements)e.disabled=busy||phase==='open';$('#add-question').disabled=busy||phase==='open';document.querySelectorAll('[data-start]').forEach(b=>{b.disabled=busy||!['lobby','revealed'].includes(phase)||b.dataset.played==='true';});document.querySelectorAll('[data-edit]').forEach(b=>b.disabled=busy||phase==='open');}
function renderQuestions(){const list=$('#question-list');list.replaceChildren();$('#question-count').textContent=`(${room.questions.length})`;room.questions.forEach((q,i)=>{const played=Object.values(room.rounds||{}).some(r=>r.question.id===q.id);const row=node('div','question-row');row.append(node('span','question-index',String(i+1).padStart(2,'0')));const detail=node('div','question-detail');detail.append(node('strong','',q.title),node('small','muted',`${q.seconds} วินาที · ${q.correct==null?'ความคิดเห็น · ไม่มีคะแนน':'มีคะแนน'}${played?' · เล่นแล้ว':''}`));row.append(detail);const actions=node('div','actions');const edit=node('button','subtle','แก้ไข');edit.dataset.edit=q.id;edit.onclick=()=>editQuestion(q);const start=node('button','button',played?'เล่นแล้ว':'เริ่มข้อ');start.dataset.start=q.id;start.dataset.played=String(played);start.onclick=()=>run(()=>command('start',{questionId:q.id}));actions.append(edit,start);row.append(actions);list.append(row);});updateControls();}
async function command(action,data={}){const r=await api(action,{room:room.code,...data},auth());state=r.state;await loadRoom();notify('อัปเดตห้องแล้ว');}
async function save(questions=room.questions){const settings={};for(const k of ['base','speed','steady','capacity'])settings[k]=Number($(`#setting-${k}`).value);settings.showDistribution=$('#setting-distribution').checked;settings.shuffleQuestions=$('#setting-shuffle').checked;await command('save',{title:$('#setting-title').value,groups:$('#setting-groups').value.split('\n').map(v=>v.trim()).filter(Boolean),settings,questions});}
function optionChoices(value){const options=$('#q-options').value.split('\n').map(v=>v.trim()).filter(Boolean);const select=$('#q-correct');const previous=value===undefined?select.value:value;select.replaceChildren(node('option','','ไม่มีถูกผิด / ไม่คิดคะแนน'));select.firstChild.value='';options.forEach((s,i)=>{const o=node('option','',`${i+1}. ${s}`);o.value=String(i);select.append(o);});select.value=previous===null?'':String(previous??'');}
function updateQuestionPreview(){const image=$('#q-image').value.trim(),preview=$('#q-preview');preview.hidden=!image;if(image)preview.src=image;}
function editQuestion(q){editing=q?.id||null;$('#q-title').value=q?.title||'';$('#q-image').value=q?.image||'';updateQuestionPreview();$('#q-source').value=q?.source||'';$('#q-options').value=(q?.options||['ใช่','ไม่ใช่']).join('\n');$('#q-seconds').value=q?.seconds||30;$('#q-explanation').value=q?.explanation||'';optionChoices(q?.correct??null);$('#delete-question').hidden=!q;$('#question-error').textContent='';$('#question-dialog').showModal();}
$('#login-form').onsubmit=e=>{e.preventDefault();run(async()=>{const r=await api('login',{password:$('#password').value});localStorage.setItem('workshop-admin',r.token);$('#password').value='';$('#notice').hidden=true;await rooms();});};
$('#password-form').onsubmit=e=>{e.preventDefault();run(async()=>{await api('changePassword',{currentPassword:$('#current-password').value,newPassword:$('#new-password').value,confirmPassword:$('#confirm-password').value},auth());e.target.reset();notify('เปลี่ยนรหัสผ่านแล้ว กรุณาใช้รหัสใหม่ในการเข้าสู่ระบบครั้งถัดไป');});};
$('#logout').onclick=logout;$('#back-rooms').onclick=()=>run(rooms);
$('#next-question').onclick=()=>run(()=>command('start',{next:true}));
$('#create').onclick=()=>run(async()=>{const r=await api('create',{},auth());await openRoom(r.room.code);});
$('#close-round').onclick=()=>run(()=>command('close'));$('#reveal').onclick=()=>run(()=>command('reveal'));
$('#finish').onclick=()=>{if(confirm('จบกิจกรรมและปิดรับผู้เล่นในห้องนี้?'))run(()=>command('finish'));};
$('#admission').onclick=()=>run(()=>command('admission',{accepting:!state.accepting}));
$('#copy-link').onclick=()=>copy(joinUrl(room.code,c));$('#export').onclick=()=>state&&csvDownload(state);
$('#settings-form').onsubmit=e=>{e.preventDefault();run(()=>save());};$('#add-question').onclick=()=>editQuestion();$('#cancel-question').onclick=()=>$('#question-dialog').close();$('#q-options').oninput=()=>optionChoices();$('#q-image').oninput=updateQuestionPreview;$('#q-preview').onerror=()=>$('#q-preview').hidden=true;
$('#question-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;try{const q={id:editing||crypto.randomUUID(),title:$('#q-title').value,image:$('#q-image').value,source:$('#q-source').value,options:$('#q-options').value.split('\n').map(s=>s.trim()).filter(Boolean),correct:$('#q-correct').value===''?null:Number($('#q-correct').value),seconds:Number($('#q-seconds').value),explanation:$('#q-explanation').value};const questions=editing?room.questions.map(v=>v.id===editing?q:v):[...room.questions,q];await save(questions);$('#question-dialog').close();}catch(e){$('#question-error').textContent=e.message;}finally{busy=false;updateControls();}};
$('#delete-question').onclick=async()=>{if(!editing||busy||!confirm('ลบคำถามนี้จากคลัง? ผลรอบที่เล่นแล้วจะยังคงอยู่'))return;busy=true;try{await save(room.questions.filter(q=>q.id!==editing));$('#question-dialog').close();}catch(e){$('#question-error').textContent=e.message;}finally{busy=false;updateControls();}};
setInterval(updateControls,200);
try{c=await config();if(!c.configured)$('#login-form').querySelector('button').disabled=true;else if(auth())await run(rooms);}catch(e){notify(e.message,true);}
