import {$,node,api,config,notify,subscribe,secondsLeft,roomCode,joinUrl,scoreList,formatMs} from './shared.js';
let state,c;const code=roomCode();
function render(s){state=s;$('#display-title').textContent=s.title;$('#lobby').hidden=!!s.round||s.phase==='finished';$('#question-stage').hidden=!s.round||s.phase==='finished';$('#finished').hidden=s.phase!=='finished';$('#joined').textContent=`เข้าร่วมแล้ว ${s.playerCount} คน`;scoreList($('#person-scores'),s.leaderboard,false,8);scoreList($('#group-scores'),s.groupScores,true,20);
  const r=s.round;$('#round-label').textContent=s.phase==='finished'?'ผลรวมกิจกรรม':r?`คำถามที่ ${r.number} / ${s.questionCount}`:'พร้อมแล้วมาเข้าห้องกัน';
  if(r){$('#question-title').textContent=r.title;const img=$('#question-image');img.hidden=!r.image;if(r.image&&img.getAttribute('src')!==r.image)img.src=r.image;img.onerror=()=>{img.hidden=true;notify('โหลดรูปคำถามไม่สำเร็จ ผู้สอนควรตรวจลิงก์ภาพ',true);};const source=$('#image-source');source.hidden=!r.source;if(r.source)source.href=r.source;
    const options=$('#display-options');options.replaceChildren();r.options.forEach((text,i)=>{const item=node('div',`display-option ${r.revealed&&r.correct===i?'correct':''}`);const row=node('div','option-line');row.append(node('span','answer-letter',String.fromCharCode(65+i)),node('span','option-text',text));if(r.distribution)row.append(node('strong','',`${r.distribution[i]} คน`));if(r.revealed&&r.correct===i)row.append(node('span','','✓'));item.append(row);if(r.distribution){const track=node('div','chart-track'),bar=node('div','chart-bar');bar.style.width=`${r.total?r.distribution[i]/r.total*100:0}%`;track.append(bar);item.append(track);}options.append(item);});
    $('#answer-count').textContent=`ตอบแล้ว ${r.total} / ${s.playerCount} คน${!r.distribution?' · แสดงกราฟหลังเฉลย':''}`;$('#answer-progress').style.width=`${s.playerCount?r.total/s.playerCount*100:0}%`;$('#explanation').hidden=!r.revealed;$('#explanation').textContent=r.revealed?`${r.correct==null?'คำถามแลกเปลี่ยนความคิดเห็น · ':''}${r.explanation}`:'';$('#fastest').textContent=r.fastest?.length?`ตอบถูกเร็วที่สุด: ${r.fastest.map(p=>`${p.name} (${formatMs(p.ms)})`).join(' · ')}`:'';
  }tick();}
function tick(){if(!state)return;$('#display-timer').textContent=state.phase==='open'?`${secondsLeft(state)}s`:state.phase==='revealed'?'เฉลย':'—';}
setInterval(tick,200);$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('เบราว์เซอร์นี้ไม่รองรับเต็มจอ');}};
try{c=await config();if(!/^[A-Z0-9]{6}$/.test(code))throw new Error('เปิดจอฉายจากหน้าผู้สอนเพื่อเลือกรหัสห้อง');if(c.configured){$('#display-code').textContent=code;$('#join-link').href=joinUrl(code,c);$('#qr').src=`/api/game?action=qr&room=${code}`;$('#qr').onerror=()=>notify('โหลด QR ไม่สำเร็จ ใช้รหัสห้องหรือลิงก์ผู้เล่นแทน',true);subscribe(code,c,render);}}catch(e){notify(e.message,true);}
